const PDFDocument = require("pdfkit");

class PDFGenerator {
  static async generateGradeReport(
    student,
    grades,
    gpaSummary,
    courseDetails = null,
  ) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const chunks = [];

        doc.on("data", (chunk) => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);

        // Header
        doc
          .fontSize(20)
          .fillColor("#2c3e50")
          .text("Student Grade Report", { align: "center" });

        doc.moveDown();

        // Student Info
        doc
          .fontSize(12)
          .fillColor("#333333")
          .text(`Student Name: ${student.name}`)
          .text(`Student ID: ${student.student_id}`)
          .text(`Email: ${student.email}`)
          .text(`Report Date: ${new Date().toLocaleDateString()}`);

        doc.moveDown();

        // GPA Summary
        doc
          .fontSize(14)
          .fillColor("#2c3e50")
          .text("Academic Summary", { underline: true });

        doc.fontSize(12).fillColor("#333333");

        if (gpaSummary.current_semester) {
          doc.text(
            `Current Semester GPA (${gpaSummary.current_semester.semester} ${gpaSummary.current_semester.year}): ${gpaSummary.current_semester.semester_gpa}`,
          );
        }
        doc.text(
          `Cumulative GPA: ${gpaSummary.cumulative?.cumulative_gpa || "N/A"}`,
        );
        doc.text(`Total Courses: ${gpaSummary.cumulative?.total_courses || 0}`);
        doc.text(`Total Credits: ${gpaSummary.cumulative?.total_credits || 0}`);

        doc.moveDown();

        // Grades Table
        doc
          .fontSize(14)
          .fillColor("#2c3e50")
          .text("Course Grades", { underline: true });

        doc.moveDown();

        // Table Header
        let yPos = doc.y;
        const colX = {
          course: 50,
          code: 160,
          credits: 260,
          percentage: 340,
          grade: 420,
          gpa: 490,
        };

        doc.fontSize(10).font("Helvetica-Bold").fillColor("#ffffff");

        // Draw header background
        doc.rect(45, yPos - 5, 520, 25).fill("#3498db");

        doc
          .fillColor("#ffffff")
          .text("Course Name", colX.course, yPos)
          .text("Code", colX.code, yPos)
          .text("Credits", colX.credits, yPos)
          .text("Score %", colX.percentage, yPos)
          .text("Grade", colX.grade, yPos)
          .text("GPA", colX.gpa, yPos);

        doc.font("Helvetica");
        yPos += 25;

        grades.forEach((grade) => {
          if (yPos > 700) {
            doc.addPage();
            yPos = 50;
          }

          doc
            .fillColor("#333333")
            .text(grade.course_name.substring(0, 30), colX.course, yPos)
            .text(grade.course_code, colX.code, yPos)
            .text(grade.credits.toString(), colX.credits, yPos)
            .text(`${grade.percentage}%`, colX.percentage, yPos)
            .text(grade.letter_grade, colX.grade, yPos)
            .text(grade.gpa_points.toString(), colX.gpa, yPos);

          yPos += 25;
        });

        // Footer
        const pageCount = doc.bufferedPageRange().count;
        for (let i = 0; i < pageCount; i++) {
          doc.switchToPage(i);
          doc
            .fontSize(8)
            .fillColor("#999999")
            .text(
              `Generated by Grade System - Page ${i + 1} of ${pageCount}`,
              50,
              doc.page.height - 50,
              { align: "center" },
            );
        }

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }
}

module.exports = PDFGenerator;
